_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.13
            "5": 0.18.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
architecture:
    value: CNN
batch_size:
    value: 128
classes:
    value: 10
dataset:
    value: MNIST
epochs:
    value: 5
kernels:
    value:
        - 16
        - 32
learning_rate:
    value: 0.005
